tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_acls_reset
    config:
       bucket_count: 25
       user_count: 25
       objects_count: 25
       min_file_size: 50
       max_file_size: 60