tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_Mbuckets_with_Nobjects
    config:
      user_count: 1
      bucket_count: 25
      objects_count: 25
      min_file_size: 50
      max_file_size: 60