tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_multipart_upload_cancel
    config:
       user_count: 25
       bucket_count: 25
       break_at_part_no: 70
       min_file_size: 800
       max_file_size: 1000